# Generated by Django 4.1.4 on 2023-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_token',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
