# Generated by Django 4.1.4 on 2023-05-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_jwt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
