# Generated by Django 4.1.4 on 2023-05-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
