# Generated by Django 4.1.4 on 2023-05-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.EmailField(max_length=254, verbose_name='Subscriber Email')),
            ],
            options={
                'db_table': 'Subscribers',
            },
        ),
    ]
