# Generated by Django 4.1.4 on 2023-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_subscribermodel_subscriber_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribermodel',
            name='subscriber_email',
            field=models.EmailField(max_length=254, verbose_name='Subscriber Email'),
        ),
    ]
