# Generated by Django 4.1.4 on 2023-04-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
