# Generated by Django 4.1.4 on 2023-04-28 10:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_alter_user_options_remove_user_token_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is Available'),
        ),
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='Item Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
