# Generated by Django 4.1.4 on 2023-05-01 18:31

import apps.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_items_is_available_items_item_image_alter_user_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
