# Generated by Django 4.1.4 on 2023-05-02 05:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_user_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Display Picture'),
        ),
    ]
